name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore NuGet packages
      run: nuget restore DotKill.sln
    - name: Build
      run: msbuild DotKill.sln /p:Configuration=Release 
