Run actions/upload-release-asset@v1
  with:
    upload_url: https://api.github.com/repos/dewee-dev/DotKill-Unpacker/releases{/id}
    asset_path: DotKill-Unpacker-4.zip
    asset_name: DotKill-Unpacker-4.zip
    asset_content_type: application/zip
  env:
    GITHUB_TOKEN: ***
Error: ENOENT: no such file or directory, stat 'D:\a\DotKill-Unpacker\DotKill-Unpacker\DotKill-Unpacker-4.zip'
